//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_Operations.DataAcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cpe_devEntities1 : DbContext
    {
        public cpe_devEntities1()
            : base("name=cpe_devEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CpeEntry> CpeEntries { get; set; }
        public virtual DbSet<CpeEntryDataPointValue> CpeEntryDataPointValues { get; set; }
        public virtual DbSet<DataPointDefinition> DataPointDefinitions { get; set; }
    }
}
