//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_Operations.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpeEntryDataPointValue
    {
        public int Id { get; set; }
        public int DataPointDefinitionId { get; set; }
        public string Value { get; set; }
        public bool IsBlobValue { get; set; }
        public byte[] BlobValue { get; set; }
        public string BlobFileName { get; set; }
        public Nullable<int> CpeDefinitionId { get; set; }
        public int CPEEntryId { get; set; }
    
        public virtual CpeEntry CpeEntry { get; set; }
        public virtual DataPointDefinition DataPointDefinition { get; set; }
    }
}
