//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_Operations.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpeEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CpeEntry()
        {
            this.CpeEntryDataPointValues = new HashSet<CpeEntryDataPointValue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CpeDefinitionId { get; set; }
        public Nullable<int> CpeDefinitionVariantId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<int> PaperMachineId { get; set; }
        public Nullable<int> PrimaryBrandId { get; set; }
        public Nullable<int> InspectedBrandId { get; set; }
        public string InspectorName { get; set; }
        public string ShortNote { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<int> LockingUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpeEntryDataPointValue> CpeEntryDataPointValues { get; set; }
    }
}
