//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR_Operations.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPointDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataPointDefinition()
        {
            this.CpeEntryDataPointValues = new HashSet<CpeEntryDataPointValue>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<int> CpeDefinitionId { get; set; }
        public Nullable<int> DataSetDefinitionId { get; set; }
        public Nullable<int> DataTypeId { get; set; }
        public int IsCalculated { get; set; }
        public string CalculationFunction { get; set; }
        public int IsConstantValue { get; set; }
        public string ConstantValue { get; set; }
        public string DPShortName { get; set; }
        public string DataSetDisplayOptionsJson { get; set; }
        public Nullable<int> VariantId { get; set; }
        public string Minimum { get; set; }
        public string Target { get; set; }
        public string Maximum { get; set; }
        public string IsRequired { get; set; }
        public string InputMask { get; set; }
        public string InvalidMessage { get; set; }
        public string ValidateFunction { get; set; }
        public Nullable<int> TabIndex { get; set; }
        public string Range { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpeEntryDataPointValue> CpeEntryDataPointValues { get; set; }
    }
}
